### ISSUE TITLE
Ensure IIIF-Manifest Gem Presentation 3 changes cover changes in spec

### ISSUE THREAD

**Issue by bkeese** [samvera-labs/avalon-bundle#116]
### Descriptive summary

IIIF has released a change log for the Presentation 3.0 spec: http://iiif.io/api/presentation/3.0/change-log/#112-use-web-annotation-data-model

Ensure IIIF_Manifest gem covers all changes that are critical for Avalon's functioning. We will note what we need for our manifest and ensure those are implemented.

### Done looks like

- IIIF manifest gem has all changes from the changelog that are important for rendering Avalon style manifest

Child of #87

**Comment by joncameron** [comment]
One thing that came up in planning was the change of "description" to "summary" which is intended to be a shorter brief summary text than what we might be putting in now (the value in the abstract field).

**Comment by yingfeng-iu** [comment]
I added "TODO: issue 116" items where I think changes are needed, and commit that to branch v3-review under iiif-manifest (strangely, 2 commits from v3_range_improvements" also show up there, even though I explicitly rebased my changes on top of  v3_range_improvements). Following is a list of V3 changes I'm not sure we've addressed so far, and would like to review with another developer:

1.3.5. Require a JSON object for all non-enumerable resources
2.1.1. Add posterCanvas for associated content
2.1.3. Add timeMode on Annotation
2.1.4. Add auto-advance for behavior
2.1.5. Add thumbnail-nav for behavior
2.1.6. Add repeat for behavior
2.1.7. Allow Canvases to be treated as Content Resources
2.2.1. Add language on external resources
2.2.2. Add no-nav, unordered, hidden for behavior
2.2.3. Add together for behavior
2.2.4. Add supplementing for motivation
2.3.2. Remove per-class URI patterns, instead make general recommendations
2.3.3. Allow external Ranges

**Comment by bkeese** [comment]
I think only the first two (1.3.5 and 2.1.1) are relevant and need further investigation.

**Comment by yingfeng-iu** [comment]
From the manifest example on florin (the unchroom one) and tests on my local env, I'm seeing that currently, 
- the manifest and canvas labels are plain text instead of language hash; 
- the metadata label-value pairs though do have correct language map; 
- also the newly added structure nodes (ranges) all have language map on the labels.
- I didn't find "summary" property on manifest, but instead I see it in metadata. Shouldn't it be the other way around, i.e. have summary as manifest property, and optionally have "description" as one of the metadata?
