### ISSUE TITLE
Identify Controlled Vocabularies For Audiovisual Work

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#131]
### Description
Controlled vocabularies are part of the profile of fields in an Audiovisual work. We need to decide what these will be. Moving away from MODS releases us from a lot of requirements that were necessary, and @metadataists will have to speak to that.

### Done Looks Like
- Identify the fields that have controlled vocabulary values
- Metadataists confirm values for controlled vocabulary
- Controlled vocabulary values are documented for implementation

child of https://github.com/samvera-labs/avalon-bundle/issues/175

**Comment by davidschober** [comment]
possibly put in .2

**Comment by joncameron** [comment]
May already be in progress or partially completed as part of active metadata work.

**Comment by jlhardes** [comment]
Updated working AV model spreadsheet to indicate language and spatial (temporal subject) can have controlled vocabularies applied now. Rights and license also added with controlled vocabularies because default Hyrax will give those to us (they are new fields for Avalon).

https://docs.google.com/spreadsheets/d/1SN3k3GYktr3Nr7oU-M8mSBaOzoYBjeLClG4DcnbUj_s/edit?usp=sharing

Made suggestions for subject, creator, contributor, genre to introduce controlled vocabularies but complicated by migration and catalog record import issues. Also some of these require property changes to accommodate URI values.

**Comment by jenyoung** [comment]
Talked to developers, going to plan for having fields for controlled (URI) and uncontrolled (text) metadata for subject, creator, genre, and contributor.
