### ISSUE TITLE
Identify metadata for Files / Filesets, apply to model

### ISSUE THREAD

**Issue by jenyoung** [samvera-labs/avalon-bundle#169]
Description:
Identify metadata for Files / Filesets, apply to model

Done looks like:

- [x] Metadata identified that needs to be added to model

child of https://github.com/samvera-labs/avalon-bundle/issues/227

**Comment by jlhardes** [comment]
What is showing on the dev site is a GenericWork that contains a FileSet that has one or more Files. 

I compared what is stored in Fedora on the dev site to the current Avalon Metadata Profile (https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Metadata+Profile).

If the properties on the current MediaObject class should be on the GenericWork now (which should maybe actually be the new AudiovisualWork, I don't know) that is missing some properties still but this issue is about FileSet and File so I won't include that here.

FileSet

We don't have any properties from the current Avalon Metadata Profile that map to FileSet so I don't have anything to add, unless Encoding Class properties could/should go here.

File

This seems to map from MasterFile properties so I am seeing the following properties that still need to be included:

ebucore:title
ebucore:locator
ebucore:duration
ebucore:aspectRatio
ebucore:width
ebucore:height
ebucore:hasFormat
loc:local
ebucore:comments
avalon:posterOffset 
avalon:thumbnailOffset

I don’t see anything that represents the Derivative Class or Encoding Class so I’m not sure how or where those properties should come in. Collection, Lease, and Permalink all seem to be managed by Hyrax already so I don’t think there’s anything to bring in on File or FileSet for those.

**Comment by jlhardes** [comment]
Previous approach isn't right. MasterFile properties are probably more likely to map to OriginalFile properties on File but some might be able to go on FileSet as well. Derivative is the same way - there's a File that can take those properties but there might be some Derivative properties that can apply to FileSet in practice. Encoding properties are also unclear if they go on a particular type of File only or can be applied to FileSet. Julie and Jen setting up discussion with @cjcolvar to sort out.

**Comment by jlhardes** [comment]
@cjcolvar and @jenyoung and I have discussed and arrived at the attached spreadsheet of technical metadata properties, most of them mapped from the current [Avalon Metadata Profile](https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Metadata+Profile). Color coding legend included in Column F (just in case you don't see it at first).
[technicalMD_Avalon7.xlsx](https://github.com/samvera-labs/avalon-bundle/files/3398633/technicalMD_Avalon7.xlsx)
