### ISSUE TITLE
Verify that Avalon .2 Work Type Spec is Fully Implemented

### ISSUE THREAD

**Issue by cjcolvar** [samvera-labs/avalon-bundle#170]
## Description

Checking to make sure that 0.2 is fully implemented, and being more thorough in the spreadsheet— checking off when properties are implemented in code.

## Done looks like
- [x] Verify if 0.2 is implemented
- [x]  Create issue(s) for things that are not implemented yet, if they exist
- [x] Add a checkbox to the spec spreadsheet to indicate whether properties have been implemented or not (for future reference)

child of https://github.com/samvera-labs/avalon-bundle/issues/175

**Comment by joncameron** [comment]
Julie notes that 0.2 is already implemented, based on our last demo. It would be good to do one last check.

**Comment by jlhardes** [comment]
Added a work to test system but need to verify properties on object in Fedora repo. Requested access to repo. Seeing that identifiers are currently separate fields but maybe should be drop-down list like Notes?

**Comment by jlhardes** [comment]
After reviewing properties in Fedora, seeing the following:

- CC license being stored as dcterms:rights but should be dcterms:license
- dcterms:spatial should be URI value instead of literal (range defined as URI: http://dublincore.org/documents/dcmi-terms/#terms-spatial)
- language is being stored as literal with dc:language but we want that to be controlled vocab stored as URI with dcterms:language

dcterms:spatial is going to be incorrect until we can implement a controlled vocab behind it and have URI values. We could consider using dc:coverage (http://purl.org/dc/elements/1.1/coverage), which can take a literal value, if we think that works for this field. We want Location/Geographic Subject to be a controlled vocab but this would make it more like the Language field where we are storing the info we have now correctly (literal value with dc:language) but we want this to be a controlled vocab term (so a URI with dcterms:language).

**Comment by jlhardes** [comment]
Audiovisual Work Model spreadsheet with checkbox column for Implemented in Worktype .2: https://docs.google.com/spreadsheets/d/1SN3k3GYktr3Nr7oU-M8mSBaOzoYBjeLClG4DcnbUj_s/edit?usp=sharing
