### ISSUE TITLE
Lay out core requirements for matterhorn replacement

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#207]
## Description

After our initial meeting we came up with a long list of what we'd like to see. We need to refine that list to a set of core requirements and identify an MVP

## Done looks like

- A document is generated describing core requirements and separately an MVP
- A meeting is schedule to work on this document

Notes:
https://northwestern.box.com/s/4smygsjak4c09o7qrep4xn1jxpqutfxr

Core Requirements:
https://northwestern.app.box.com/notes/312769608503?s=7gp0gfaqpbc4a6xswrhw6yhf3fa480vn

**Comment by davidschober** [comment]
@cjcolvar we wrote these up, can you review and move to done. Jon and I stubbed out issues.

**Comment by cjcolvar** [comment]
@joncameron @davidschober I think that looks good with one exception.  The way we're heading right now with the dashboard provided by `active_encode` filtering by collection is hard within the dashboard because `active_encode` doesn't know anything about Hyrax models.  There are three solutions to this I could think of: 
1) Create different encoding classes per collection based on collection name (by product is that this could also provide a way to have collection specific encoding options but might cause other issues)
2) Create a separate dashboard for a Hyrax specific view of encodes
3) Display encoding information in the existing collection dashboard view or search results or some other pre-existing Hyrax page

**Comment by joncameron** [comment]
I've added Chris' notes to the document. This is something to tease out, especially in how it relates to how we want to lay out the dashboard, how it looks for different audiences (collection manager vs admin).
