### ISSUE TITLE
Query Status Endpoint for ActiveEncode Job

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#254]
### Description

The UI displays status information obtained by querying the ActiveEncode endpoint. This supersedes the Hyrax "your job's processing; refresh" message so we can show dynamic status much like Avalon 6.

### Done looks like 

- a user sees a progress notification on an item page
- bonus points! a status bar updates with polling (otherwise we need to write new issues)

child of https://github.com/samvera-labs/avalon-bundle/issues/250

**Comment by cjcolvar** [comment]
Work being done in 3 repos: 
https://github.com/samvera/hydra-derivatives/tree/active_encode_global_id
https://github.com/samvera-labs/hyrax-active_encode/tree/encode_global_id
https://github.com/samvera-labs/avalon-bundle/tree/encode_status

We will probably want to go back and expand the encode record endpoint in active_encode to take a global id instead of just the sql_id when we create a component that can poll the server and power a progress bar.

**Comment by cjcolvar** [comment]
I just realized that my approach is flawed and will only return status information when the encode is complete (success, failed, or timed out).  I'll need to either override hydra-derivatives or add a callback mechanism so that we can store the encode's global id before it starts to block.

**Comment by cjcolvar** [comment]
New approach is in https://github.com/samvera-labs/hyrax-active_encode/pull/14
and https://github.com/samvera-labs/avalon-bundle/pull/270
