### ISSUE TITLE
Avalon-style Leases Investigation

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#320]

**Comment by cjcolvar** [comment]
Currently embargoes and leases are implemented in hydra-access-controls as a new fedora object that belongs to a work.  This object has a few fields describing the changes to visibility that should happen and when.  Hyrax provides UI for creating these objects but doesn't provide any automated way to enforce them.  It is expected that a user would manually click a button to take the visibility change described in the embargo or lease object.  Avalon style leases (which I'm now calling "time limited permissions") could be implemented in the same way which would simplify solr queries from the avalon 6 approach that uses APOs.  In this case we could create a fedora object that would hold time limited permissions and expect a cron job or user to perform the change described in the object (e.g. grant 'joe@smith.com' view access on 1/1/19 or revoke view access on 2/2/19).  Normal permissions for an object in fedora are stored in a separate top-level access control object with individual permission grants as new objects contained within.  If we followed the same pattern for time limited permissions I think we would needlessly be creating too many objects which would add to network and processing loads potentially leading to performance issues.  Instead I'd recommend storing a hashified form (maybe JSON) for each time limited permission using the same RDF predicate.  At that point the code that would need to be written in hydra-access-controls should have a similar api to normal permissions but add a begin and end date field and serialize the whole thing as described above.  In Hyrax (or avalon-bundle) we'd have to create UI for creating, editing, and deleting (and possibly activating/deactivating) these time limited permissions as well as any automated process for applying the permission changes they describe.  I don't expect the work in hydra-access-controls to be too difficult (maybe a 5) and would probably involve my time sooner or later since I'm the PO for hydra-access-controls.  The UI work in hyrax would probably be a 8 or 13.  The automated part shouldn't be much different than what we would setup for embargoes or leases so I'm not estimating that work as part of the permissions work.

**Comment by mcwhitaker** [comment]
@cjcolvar Thanks for this summary. About the _automated part_ that is similar to hyrax embargoes and leases, could you please estimate that? For Avalon v7 with parity to v6 we actually don't need embargoes and leases, so having to do that for parity is additional work. Is this automated part something that we could hire out or would it be better to do it in-house?

**Comment by cjcolvar** [comment]
The automated part is in-house infrastructure since we'd have to setup cron jobs or some other sort of mechanism for applying these changes.  I think it would only be a 3 to 5.  5 because we haven't setup anything like that yet for avalon-bundle.

**Comment by phuongdh** [comment]
There're multiple options depending on how we implement this. Cronless: when user requests an item, dynamically check the time-limited permission Fedora object and grant the access, not sure how gated discovery and access revocation would work. Cron: just like Chris described, but for Docker setup we'll need to run the cron job in a separated container with the app context.
