### ISSUE TITLE
Directory Groups Investigation

### ISSUE THREAD

**Issue by joncameron** [samvera-labs/avalon-bundle#321]
how to hook up LDAP or some other service to populate user groups; lots of examples; how to do this from Avalon perspective vs specific institution

description might be in another issue/epic as well

Done looks like
- investigate with approach in mind
- rough estimate of amount of work

**Comment by cjcolvar** [comment]
Avalon 6 only has support for LDAP groups (https://wiki.dlib.indiana.edu/display/VarVideo/LDAP+Access+Control), do we need to support anything else or make seams in the code to allow for easy plugging in of other services (e.g. grouper)?  
Avalon's LDAP code has already been extracted (and modified/improved slightly) and used at IU in a few hyrax based apps: https://github.com/IUBLibTech/ldap_groups_lookup.  An older community LDAP library also exists: https://github.com/samvera-labs/hydra-ldap.  If we're just looking at feature parity then I think using `ldap_groups_lookup` would be the easiest and would be a 2-3 to integrate.  The only piece of work that I think it would need is being able to read configuration from environment variables for the docker/cloud environments which should only be a 3.
Creating a seam for other sources of groups should be pretty easy (2-3) since it would just need a little bit of code, some tests, and documentation.

**Comment by mcwhitaker** [comment]
I know 2-3 points sounds little, but I am personally getting to a point where I want nothing more than parity. We need to get further in our implementation of Avalon 7. My two cents.
