### ISSUE TITLE
IIIF Prezi 3 AV Cookbook Recipes

### ISSUE THREAD

**Issue by mcwhitaker** [samvera-labs/avalon-bundle#356]
### Descriptive summary

The IIIF editors have asked the community to help with the creation of _Cookbook Recipes_ for Prezi 3 manifests. At IU we can help with the AV _cookbook recipes_. Recipes will be reviewed during an _office hours_ call at the end of September and more recipes will be reviewed and created as part of the IIIF Working Meeting in Ann Arbor in early November. 

This ticket is for the creation of at least one IIIF Prezi 3 AV _Cookbook Recipe_ in preparation for the September review. The AV recipes are listed here: https://github.com/IIIF/cookbook-recipes/labels/av. 

The content to be used needs to be in the IIIF S3 bucket. The access is via URLs of the form, for example, http://iiif-av.s3.amazonaws.com/examples/indiana/lunchroom_manners/high/lunchroom_manners_1024kb.mp4

IU has provided some files currently in the .../examples/indiana folder:
 
.../30-minute-clock/medium/30-minute-clock.mp4
.../lunchroom_manners/high/lunchroom_manners_1024kb.mp4
.../lunchroom_manners/low/lunchroom_manners_256kb.mp4
.../lunchroom_manners/lunchroom_manners.vtt
.../lunchroom_manners/medium/lunchroom_manners_512kb.mp4
.../mahler-symphony-3/CD1/high/320Kbps.mp4
.../mahler-symphony-3/CD1/medium/128Kbps.mp4
.../mahler-symphony-3/CD2/high/320Kbps.mp4
.../mahler-symphony-3/CD2/medium/128Kbps.mp4
.../parliamentary/high/parliamentary-procedure-in-action.mp4
.../parliamentary/low/parliamentary-procedure-in-action.mp4
.../parliamentary/medium/parliamentary-procedure-in-action.mp4
.../sohio/high/sohio.mp4
.../sohio/low/sohio.mp4
.../sohio/medium/sohio.mp4
.../volleyball/high/volleyball-for-boys.mp4
.../volleyball/low/volleyball-for-boys.mp4
.../volleyball/medium/volleyball-for-boys.mp4

We should probably add one example with adaptive bitrate streaming as there is the need of a recipe for this case.

Another ticket will be created later for more recipes if needed.

**Comment by cjcolvar** [comment]
@mcwhitaker How about doing the opera recipes first instead of the adaptive streaming one?  I'm not sure I really understand what is expected in that one.  I think the opera ones will be more straight-forward.  The holdup on the opera recipes was getting shareable content, right?  Maybe we could work on it without the media?

**Comment by mcwhitaker** [comment]
@cjcolvar Let me know when it would work for you to do this.

**Comment by cjcolvar** [comment]
This is what I have for the opera recipes.
https://github.com/avalonmediasystem/cookbook-recipes/commit/e6fac6647493fb4d607b72fc4221f622d1825286
We’ll need to cleanup the manifests once we have non-MCO content urls.  Possibly taking the choice and auth out of the two real world examples as well.
I used a IU Performance of Don Giovanni since it already had a good structure.  FWIW The video item for it from MCO is public but the audio item I used is not.

It might be a little easier to read outside of the diff.  Here are the three recipes I worked on:
https://github.com/avalonmediasystem/cookbook-recipes/tree/av_recipes/recipe/0026-toc-opera
https://github.com/avalonmediasystem/cookbook-recipes/tree/av_recipes/recipe/0064-opera-one-canvas
https://github.com/avalonmediasystem/cookbook-recipes/tree/av_recipes/recipe/0065-opera-multiple-canvases
