### ISSUE TITLE
Avalon Player Can Be Navigated Using Structural Metadata

### ISSUE THREAD

**Issue by davidschober** [samvera-labs/avalon-bundle#99]
---

Migrated from https://github.com/avalonmediasystem/avalon/issues/2204
Originally created by @joncameron on *Tue, 08 Aug 2017 21:07:16 GMT*

---
### Description
Structural metadata (structure within) for a section will be shown on the page for a work. Click links in this structural metadata that refers to time spans should cause the player to navigate to the beginning offset of that span.

## Done looks like
- we have a ui similar to stand alone player

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners can we turn this story into an epic for updating the standalone player and using it within avalon-bundle?  The standalone player already renders the structural metadata and handles navigation of it.  So instead of pulling code from the standalone player into avalon-bundle, making the jump and pulling in the whole standalone player.  It's your call if this is better as a different story instead of hijacking this one.

Children of the epic would be:
avalon-iiif-manifest: #22, #23, #24
avalon-bundle: #111

**Comment by joncameron** [comment]
Superceded by an epic.
